version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: nexumi-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: nexumi123
      MONGO_INITDB_DATABASE: nexumi_game
    volumes:
      - mongo-data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - nexumi-network

  # MongoDB Express (Web UI for database management)
  mongo-express:
    image: mongo-express:1.0
    container_name: nexumi-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: nexumi123
      ME_CONFIG_MONGODB_URL: mongodb://admin:nexumi123@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - nexumi-network

  # Optional: API Server for Godot-MongoDB communication
  # nexumi-api:
  #   build: ./api
  #   container_name: nexumi-api
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     MONGODB_URI: mongodb://admin:nexumi123@mongodb:27017
  #     MONGODB_DATABASE: nexumi_game
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - nexumi-network

volumes:
  mongo-data:
    driver: local

networks:
  nexumi-network:
    driver: bridge 